
setwd("C:/Rob/courses etc/Data Science/Exploratory/project 1")
myData <- read.table("household_power_consumption.txt",sep = ";",dec=",",header=TRUE,stringsAsFactors = FALSE)
daysdata <- subset(myData,Date=="1/2/2007" | Date == "2/2/2007")
daysdata$Time <- paste(daysdata$Date,daysdata$Time,sep=" ")
daysdata$Time <- strptime(daysdata$Time, "%d/%m/%Y %H:%M:%S")
par(mfrow=c(2,2))
plot(daysdata$Time,daysdata$Global_active_power,type="n",ylab="Global Active Power",xlab=" ")
lines(daysdata$Time,daysdata$Global_active_power)
daysdata$Voltage <- as.numeric(daysdata$Voltage)
plot(daysdata$Time,daysdata$Voltage,ylab="Voltage",xlab="datetime",type="n")
lines(daysdata$Time,daysdata$Voltage)
daysdata$Sub_metering_1 <- as.numeric(daysdata$Sub_metering_1)
daysdata$Sub_metering_2 <- as.numeric(daysdata$Sub_metering_2)
daysdata$Sub_metering_3 <- as.numeric(daysdata$Sub_metering_3)
plot(daysdata$Time,daysdata$Sub_metering_1,type="n",ylab="Energy Sub Metering",xlab=" ")
lines(daysdata$Time,daysdata$Sub_metering_1)
lines(daysdata$Time,daysdata$Sub_metering_2,col="red")
lines(daysdata$Time,daysdata$Sub_metering_3,col="blue")
legend(x="topright",c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),col=c("black","red","blue"),lty=,lwd=2.5,bty="n",cex=0.5)
daysdata$Global_reactive_power <- as.numeric(daysdata$Global_reactive_power)
plot(daysdata$Time,daysdata$Global_reactive_power,type="n",ylab="Global_reactive_power",xlab="datetime")
lines(daysdata$Time,daysdata$Global_reactive_power)
dev.copy(png,'plot4.png', width=480, height=480)
dev.off()